opensvc/om3

core/commands/node_print_schedule.go
core/commands/object_edit_config.go
core/entrypoints/create/main.go
core/object/core_config.go
core/object/node_config.go
core/object/node_print_schedule.go
core/xconfig/object.go
drivers/poolvirtual/main.go

xconfig.NewObject now has its first argument interpreted as the config
file path, not considered to be loaded.
the following arguments are sources to load, so the cf must be passed
again to load it.
Update the calling codepath to convert to this policy.

Make object.WithConfigData() ignore the existing config file content

---

daemon/daemonapi/get_daemon_status.go
daemon/daemondata/apply_commit.go
daemon/daemondata/apply_patch.go
daemon/daemondata/data.go
daemon/daemondata/data_init.go
daemon/daemondata/hb_message.go
daemon/daemondata/heartbeats.go
daemon/daemondata/sub_refresh.go
daemon/discover/svcagg.go
daemon/hb/main.go
util/callcount/main.go
util/pubsub/main.go

This pull request fix possible daemon restart hangs because of not anymore processed commands from channels, after context is done
- daemondata:  hbRecvQ
- discover: svcaggCmdC 
- hb msgToTx: HBSendQ
- hb msgFromRx: HBRecvMsgQ
- callcount on its cmd channel
Another possible hang may occur during daemondata.queueNewHbMsg (write to drained chan from hb), so
now daemondata.queueNewHbMsg use ctx to abort when ctx is done

Fix possible daemon restart hang

---

core/event/main.go
daemon/daemonapi/get_daemon_events.go
daemon/msgbus/messages.go

Always show event data, even when Bytes() is not implemented.

Split msgbus message Bytes() into Bytes() and String()

---

core/instance/instance.go
core/instance/monitor.go
core/instance/monitor_test.go
core/instance/testdata/monitor.json
core/instance/testdata/monitor_deprecated_restart.json
core/resource/resource.go
core/xconfig/main.go
daemon/daemondata/instance_config.go
daemon/daemondata/main_test.go
daemon/daemondata/stats.go
daemon/monitor/imon/crm_actions.go
daemon/monitor/imon/main.go
daemon/monitor/imon/main_cmd.go
daemon/monitor/imon/orchestration.go
daemon/monitor/imon/orchestration_frozen.go
daemon/monitor/imon/orchestration_provisioned.go
daemon/monitor/imon/orchestration_resource_restart.go
daemon/monitor/imon/orchestration_stopped.go
daemon/monitor/imon/orchestration_thawed.go
daemon/monitor/imon/orchestration_unprovisioned.go
daemon/monitor/instcfg/main.go
daemon/monitor/nmon/orchestration_frozen.go
daemon/monitor/nmon/orchestration_thawed.go
daemon/msgbus/messages.go
daemon/scheduler/main.go
go.mod
go.sum
util/toc/bsd.go
util/toc/dummy.go
util/toc/linux.go

* when a resource goes down on an instance with local_expect
'started' try to restart it '<rid>.restart' times (default 0)
with '<rid>.restart_delay' delay.
* if the resource has '<rid>.monitor=true' and not restartable
after all retries, emit a InstanceMonitorAction event, and
execute the 'DEFAULT.monitor_action'.
example event:
{
"kind": "InstanceMonitorAction",
"id": 1,
"t": "2023-01-12T17:47:53.001330232+01:00",
"data": {
"Path": "foo001",
"Node": "dev2n1",
"Action": "freeze_stop",
"RID": "fs#1"
}
}
* if multiple resource are to be restarted, group them in a
single CRM command, using the greatest restart_delay.
* available monitor actions:
implemented:
MonitorActionFreezeStop MonitorAction = "freeze_stop"
to be implemented:
MonitorActionCrash      MonitorAction = "crash" …

Implement the resource restart

---

core/cluster/cluster.go
core/cluster/cluster_test.go
core/cluster/config.go
core/cluster/frame.go
core/clusterip/main.go
core/commands/object_print_status.go
core/monitor/main.go
core/network/main.go
core/node/config.go
daemon/daemonapi/get_daemon_events_test.go
daemon/daemondata/cluster_config.go
daemon/daemondata/cluster_status.go
daemon/daemondata/data.go
daemon/daemondata/data_init.go
daemon/daemondata/main_test.go
daemon/daemondata/node_config.go
daemon/daemondata/stats.go
daemon/monitor/instcfg/main.go
daemon/monitor/nmon/main.go
daemon/monitor/nmon/main_cmd.go
daemon/msgbus/messages.go
util/pubsub/main.go
util/pubsub/main_test.go

Not exposed in daemon status nor events streamed by the api, but available to the internal NodeConfigUpdated subscribers.
All users of rawconfig.LoadSections().Secret can not use this as a replacement.

Add a secret private field to node.Config

---

daemon/imon/orchestration_resource_restart.go

Example:
16:21:57.087 INF resource fs#1 status down, restart remaining 0 out of 0 func=imon n=dev1n1 object=foo113 sid=bec5cdee-4c46-41ed-94e1-8ecc49ae1e74

Fix undue resource restart daemon log messages

---

cmd/factory.go
cmd/node.go
core/commands/node_version.go
core/object/node_push_asset.go
core/version/main.go
util/version/main.go
util/version/text/README

version.Version() returns a string containing either the content of util/version/VERSION (which is created or updated by the packaging automation), or the build info release (ie the git HEAD commit id at build time).
Example VERSION file generation:
git describe --tags >util/version/VERSION

Implement "om node version"

---

daemon/imon/crm_actions.go
daemon/msgbus/messages.go
daemon/nmon/crm_actions.go
daemon/scheduler/jobs.go
daemon/scheduler/main.go

om node event --filter Exec,path=bar --filter ExecSuccess,path=bar --filter ExecFailed,path=bar --template '{{printf "%s from %s %v %s\n" .kind .data.origin .data.labels .data.command}}'
Exec from imon map[node:node1 origin:imon path:bar] om bar status -r
ExecSuccess from imon map[node:node1 origin:imon path:bar] om bar status -r
Exec from imon map[node:node1 origin:imon path:bar] om bar provision --local --leader --disable-rollback
ExecSuccess from imon map[node:node1 origin:imon path:bar] om bar provision --local --leader --disable-rollback
Exec from scheduler map[node:node1 origin:scheduler path:bar] om bar status -r --local
ExecSuccess from scheduler map[node:node1 origin:scheduler path:bar] om bar status -r --local
Exec from imon map[node:node1 origin:imon path:bar] om bar stop …

daemon publish Exec, ExecFailed, ExecSuccess crm actions

---

cmd/factory.go
daemon/daemon/main.go
daemon/daemondata/data.go
daemon/discover/cfg.go
daemon/discover/omon.go
daemon/dns/main.go
daemon/istat/main.go
daemon/scheduler/main.go
util/pubsub/main.go
util/pubsub/main_test.go
util/pubsub/msg.go

- improves daemon memory footprint (many objects)
- prevents daemondata <-> pubsub hang during event storms

Improves daemon <-> pubsub memory footprint when many objects

---

core/rawconfig/node.go
core/rawconfig/paths.go
util/compliance/run.go

Define rawconfig.Path.Compliance as /usr/share/opensvc/compliance for packaged deployments and <head>/share/compliance/ for dev deployments.
This directory must host symlinks to the compobj bundle executable.
Example:
$ ls ... /opt/opensvc/share/compliance/
authkey -> compobj
compobj
file -> compobj
fileinc -> compobj
fileprop -> compobj
group -> compobj
group_membership -> compobj
nodeconf -> compobj
package -> compobj
sudo -> compobj
svcconf -> compobj
symlink -> compobj
sysctl -> compobj
user -> compobj

Switch the compliance commands to use native comp objects

---

util/compobj/main.go
util/compobj/main_test.go

This flag makes it easy to install the compobj symlinks in the target directory.
If the symlink target is different, recreate the symlink.
Example:
$ ./compobj -i /opt/opensvc/share/compliance/
symlink /root/dev/om3/util/compobj/compobj /opt/opensvc/share/compliance/fileprop: already exists symlink /root/dev/om3/util/compobj/compobj /opt/opensvc/share/compliance/group: already exists symlink /root/dev/om3/util/compobj/compobj /opt/opensvc/share/compliance/package: already exists symlink /root/dev/om3/util/compobj/compobj /opt/opensvc/share/compliance/svcconf: already exists symlink /root/dev/om3/util/compobj/compobj /opt/opensvc/share/compliance/symlink: already exists symlink /root/dev/om3/util/compobj/compobj /opt/opensvc/share/compliance/authkey: already exists symlink …

Add a -i flag to the compobj bundle

---

util/compobj/main.go

The regexp was too greedy and failed when a rule has more than one env var to substitute.

Fix the %%ENV:...%% substitution algo in compobj

---

core/cluster/cluster.go
core/objectselector/selection.go
daemon/daemonapi/get_daemon_status.go
daemon/daemondata/daemon_refresh.go

"om plop* mon" displayed only the objects with a local instance.
"om plop mon" displayed no match when plop has no local instance.

fix object selection and filtering issues

---

core/om/factory.go
core/om/root.go
core/ox/factory.go
core/ox/root.go

And support:
$ bin/ox -v
ox version v3.0.0-alpha10-443-gc0a6c57d
$ bin/om -v
om version v3.0.0-alpha10-443-gc0a6c57d

Hide the "o[mx] node version" commands

---

core/object/core_keywords.go
daemon/daemonapi/post_object_config_update.go
daemon/daemonhelper/main.go
daemon/runner/main.go

Example:
$ curl  -o- -k -X POST -u me:pw -H "Content-Type: application/json" "https://127.0.0.1:1215/object/path/test/svc/svc2/config/update?set=priority=2" {"detail":"","status":401,"title":"Not allowed to set priority (the root or prioritizer grant is required)"}

Return an explicit error instead of silently droping the "priority" kop

---

core/object/core_keywords.go
daemon/icfg/main.go

* default flex_target kw value changed to {flex_min}
* icfg flex_min is evaluated first and must be >=1 on svc or >=0 on vol, and must be <= n_instances whatever the kind
* icfg flex_max is evaluated next and must be >= flex_min and <= n_instances
* icfg flex_target is evaluated last and must be >= flex_min and <= flex_max

Fix flex_{min,max,target} values

---

core/object/core_action.go
core/om/flags.go
core/ox/all.go
core/ox/ccfg.go
core/ox/cfg.go
core/ox/factory.go
core/ox/flags.go
core/ox/root.go
core/ox/sec.go
core/ox/svc.go
core/ox/usr.go
core/ox/vol.go
core/tui/main.go

With this patch, the tui can be launched via:
* display only svc
* ox
* ox tui
* ox svc tui
* display only <kind> objects:
* ox <kind> tui
* ox '*/<kind>/*'
* ox '*/<kind>/*' tui
* display only objects matching <selector>:
* ox <selector>
* ox <selector> tui

More ox tui command access and filtering from the command line

---

core/tui/main.go
daemon/imon/orchestration_provisioned.go
daemon/imon/orchestration_started.go

* clear the global expect if all instances are "provision failed"
* unfreeze the instance if already provisioned and frozen

Fixes for the provision orchestration

---

core/instance/monitor.go
daemon/imon/converge_global_expect.go
daemon/imon/main_cmd.go
daemon/imon/orchestration.go
daemon/imon/orchestration_ha.go
daemon/imon/orchestration_resource_restart.go
daemon/imon/orchestration_stopped.go
daemon/msgbus/messages.go

This pull request introduces a "stopped" state in the orchestration stop process to improve handling and transitions.
The changes made include:
- Adding a "stopped" state in both the orchestrateStopped() and stop() functions
- Creating the flow: stopping -> stopped -> idle
- Utilizing the "stopped" state to change the local expectation from started -> none
These updates enhance the handling of orchestrations and ensure correct state transitions where necessary.

Introduce "stopped" state in orchestration stop process

---

core/om/flags.go
core/om/text/node-events/flag/filter
core/output/flatten.go
core/ox/flags.go
core/ox/text/node-events/flag/filter
daemon/daemonapi/get_daemon_events.go
daemon/daemonapi/get_daemon_events_test.go

Update the command flag doc to reflect the need possibilities:
Receive only events matching the filtering expression formatted as:
<kind>[,filter[,...]]
where:
<kind> is the required event kind
<filter> can be:
<key>=<value> is a required event label
<jsonpath><op><value> is required condition on the event data
where:
<jsonpath> starts with a dot and is relative to .data
<op> can be
= or !=
> or <
>= or <=
Examples:
InstanceStatusUpdated
InstanceStatusUpdated,path=svc1
InstanceStatusUpdated,path=svc1,node=n1
InstanceStatusUpdated,path=svc1,node=n1,.instance_status.frozen_at="0001-01-01T00:00:00Z"
InstanceStatusUpdated,path=svc1,node=n1,.instance_status.frozen_at>"0001-01-01T00:00:00Z"
InstanceStatusUpdated,path=svc1,node=n1,.instance_status.avail="up"

Implement more ops for event --filter ...,<jsonpath><op><val>

---

core/nodeaction/node.go
core/objectaction/object.go
daemon/daemondata/apply_patch.go
daemon/daemondata/data.go
daemon/imon/orchestration_purged.go
daemon/imon/orchestration_stopped.go
daemon/msgbus/instance_config.go
daemon/msgbus/instance_monitor.go
daemon/msgbus/instance_status.go

This pull request addresses the following issues:
1. **Fix nil pointer dereference during event filtering**:
- Added checks to ensure `Monitor`, `Status`, and `Config` fields of instances are not nil before processing.
- Prevents runtime panics caused by nil pointers during event filtering.
2. **Ensure finalization of tasks during stop failure handling in `imon`**:
- Added a missing call to `t.done()` during stop failure handling to prevent incomplete task states.
3. **Improve reliability of `--wait` during object actions**:
- Changed the waiting condition from `InstanceMonitorUpdated` to `ObjectOrchestrationEnd` for better accuracy and to avoid premature termination of the waiting process. 
These changes collectively enhance the robustness and reliability of the system

Fix event filtering and orchestration reliability issues

---

core/cluster/data.go
core/instance/data.go
core/node/data.go
core/object/actor_enter.go
core/object/data.go
core/pool/data.go
core/schedule/data.go
core/schedule/main.go
daemon/daemonsubsystem/cache.go
daemon/nmon/main.go
drivers/rescontainerocibase/executor.go
util/san/main.go

This pull request addresses several significant issues:
- **Logging Enhancements**: Logs the resource ID when the `Enter` command fails for better debugging and tracking.
- **Error Message Fix**: Corrects a typo in the error message for missing container command during the `Enter` operation.
- **DeepCopy Implementation**: Adds the missing DeepCopy method for `*Paths` and ensures the `deepCopyer` interface is implemented for relevant cached types.
- **500 Error Fix**: Resolves a server panic caused by the `GET /node/name/:nodename/schedule` endpoint due to a missing DeepCopy method in the `schedule.Table` implementation.
Pay special attention to the new DeepCopy method implementations and ensure identified logging points provide meaningful debugging information

Fix DeepCopy issues and enhance error handling for Enter command

---

core/commoncmd/main.go
core/commoncmd/node_log.go
core/commoncmd/object_log.go
core/event/sseevent/main.go
core/omcmd/node_logs.go
core/omcmd/object_clear.go
core/omcmd/object_logs.go
core/oxcmd/node_logs.go
core/oxcmd/object_clear.go
core/oxcmd/object_logs.go
core/streamlog/main.go

This pull request contains the following updates:
1. **Shared Command Functionality**:
- Introduced a shared `core/commoncmd` package for `omcmd` and `oxcmd` commands.
- Updated command implementations to use the shared functionality.
- Fixed the ignored `--node` option in `om node log` command.
2. **Stream Log Enhancements**:
- Fixed newline handling in event rendering and unmarshalling for consistency.
- Refactored methods in `Event` and `Stream` structs to use pointer receivers for efficiency.
- Removed redundant newline in the JSON renderer.
This improves output of `ox node log -o json | hl -P -h '*' -h '!node'`. 
3. **Event Handling Improvements**:
- Improved error handling for process termination.
- Handled unexpected `nil` values in event and error channels gracefully, avoiding …

[ox,om] Integrate shared command functionality and fix log -o json rendering

---

daemon/daemoncmd/main.go
daemon/daemonsys/linux.go

If the daemon stop is initiated by systemd and the system state is "stopping" (reboot or shutdown), then promote the "om daemon stop" command to a "om daemon shutdown".

Remove the need for the opensvc-services unit

---

core/object/node_keywords.go
core/object/text/kw/node/hb.disk.max_slots
core/xconfig/validate.go
daemon/daemonapi/get_node_ssh_key.go
daemon/daemonapi/put_node_ssh_trust.go
daemon/daemondata/data.go
daemon/hb/hbctrl/main.go
daemon/hb/hbdisk/device.go
daemon/hb/hbdisk/device_dummy.go
daemon/hb/hbdisk/device_linux.go
daemon/hb/hbdisk/hbrx.go
daemon/hb/hbdisk/hbtx.go
daemon/hb/hbdisk/main.go
daemon/hb/main.go

This pull request includes the following changes:
- **Command Enhancements:**
- Updated the `om cluster ssh trust` command to trust localhost in addition to peer nodes.
- Improved the SSH key comment format to include the `opensvc-cluster-root-trust@<nodename>` structure for better clarity.
- **Bug Fixes:**
- Addressed issues with unexpected `NodeStatusGenUpdates` publications in `daemondata`.
- **Improvements:**
- Incorporated a validation mechanism to handle `converters.Int` during keyword candidate checks, ensuring alerts are raised for mismatched values.
- Refactored heartbeat disk operations to enhance slot management and improve logging for easier debugging.

Refactored heartbeat disk operations to enhance slot management

---

CHANGELOG.md
core/om/daemon.go
core/om/factory.go
core/om/flags.go
core/omcmd/daemon_run.go
core/ox/flags.go
daemon/daemoncmd/main.go

So the daemon long-standing process name doesn't confuse the user into thinking the daemon is still starting.

Add a "om daemon run" command to replace "start --foreground"

---

core/object/core.go
core/object/core_config.go
core/object/factory.go
core/object/node.go
core/object/node_config.go
core/omcmd/node_doc.go
core/omcmd/object_doc.go

* Allow empty string arg in the object.New* WithConfigFile("") funcopt.O which resets the default value allocated, like /etc/opensvc/cluster.conf or /etc/opensvc/node.conf
* If the (*core).configFile or (*Node).configFile is an empty string, don't ask ini to load it, so there will not be a permission denied error when run rootless.
* Adopt the same logic for (*Node).clusterConfigFile

Allow rootless "om cluster doc" and "om node doc"

---

core/driverdb/drivers_linux.go
daemon/dns/uds.go
drivers/rescontainerdocker/caps.go
drivers/rescontainerdocker/manifest.go
drivers/rescontaineroci/caps.go
drivers/rescontaineroci/main.go
drivers/rescontainerpodman/caps.go
drivers/rescontainerpodman/manifest.go
drivers/restaskdocker/caps.go
drivers/restaskdocker/main.go
drivers/restaskdocker/manifest.go
drivers/restaskoci/caps.go
drivers/restaskoci/main.go
drivers/restaskpodman/manifest.go

This pull request includes the following changes:
- Removed redundant context check in the DNS UDS accept loop for improved readability and reduced complexity.
- Introduced an OCI task driver for dynamic container management using Docker or Podman based on system capabilities.
- Refactored driver ID handling for Docker and Podman to simplify registration and capability checks.
- Renamed invalid package name for `drivers/restaskdocker` to resolve naming issues.
- Enhanced Docker and Podman drivers to streamline integration with the unified OCI driver, improving maintainability and clarity of responsibility.

Simplify context check and unify OCI driver handling

---

drivers/rescontainerocibase/main.go

We set the --time <stop_timeout> on the docker stop command, so no need to add a wrapping context that would expire at the same timeout the command returns, leaving us no time to wrap-up (docker inspect is the first post-stop command executed, and is killed by context).

Remove the stop timeout context from the containerocibase driver

---

daemon/omon/main.go

Missing the StandyDown, StandyUp states detection in the omon algo that decides if place is non-optimal.

Fix undue "placement non-optimal" issue with standby instances

---

drivers/networkroutedbridge/main.go

This segmentation is wrong, as it leaves holes between segments:
subnet@dev2n1 = 10.123.0.0/20
subnet@dev2n2 = 10.123.64.0/20
subnet@dev2n3 = 10.123.128.0/20
Fix the algo to allocate contiguous segments:
subnet@dev2n1 = 10.123.0.0/20
subnet@dev2n2 = 10.123.16.0/20
subnet@dev2n3 = 10.123.32.0/20

Fix the routed bridge networks segmentation algo

---

core/object/config_test.go
core/xconfig/main.go

[env]
a = foo
b = {a} {a}
The `env.a` key should evaluate as `foo foo`, not trigger a infinite recursion error.
Add a test to not regress on that policy.

Fix a undue infinite recursion situation

---

core/object/actor.go
core/object/config_test.go

The 2.1 version allowed that. Ensure backward compatibility.
Add a test to avoid regression.

Allow the resources type keyword to be a reference

---

core/node/config.go
daemon/nmon/main.go
daemon/nmon/main_cmd.go

This pull request introduces a `bootstrapConfig` function to properly initialize node configuration during startup. It ensures the persistent reservation key (`prkey`) is either generated or retrieved as needed. Additionally, a `prkey` field has been added to the node configuration to maintain its value.
This change ensures reliable and consistent setup of the node manager.

Bootstrap and initialize missing `prkey` during node startup

---

CHANGELOG.md
core/om/factory.go
core/omcmd/node_config_show.go
core/omcmd/object_config_show.go
core/ox/factory.go
core/oxcmd/node_config_show.go
core/oxcmd/object_config_show.go
core/rawconfig/raw.go
drivers/resip/main.go
drivers/resiphost/arp.go
drivers/resiphost/main.go
drivers/resiphost/main_cmd.go
util/command/main.go

Use the `ip` instead of `ifconfig` that opensvc v2.1 used, as this command is deprecated.
Example: Forced label, implicit alias=false:
[ip#label1]
type = host
name = 128.0.0.11
dev = br-prd:11
netmask = 24
Example: Dynamic label, explicit alias=false:
[ip#label2]
type = host
name = 128.0.0.12
dev = br-prd
alias = false
netmask = 24
Make the ip.host resource label report the label if any:
svc1                             up
└ instances
└ dev2n1                       up     idle
├ resources
...
│ ├ ip#label1      ...../..  up     host 128.0.0.11/24 br-prd label br-prd:11
│ ├ ip#label2      ...../..  up     host 128.0.0.12/24 br-prd label br-prd:0

Implement the ip.host interface alias mode

---

core/om/text/node-events/event-kind
core/ox/text/node-events/event-kind
daemon/daemondata/daemon_hb.go
daemon/discover/cfg.go
daemon/hb/hbctrl/main.go
daemon/hb/hbctrl/main_test.go
daemon/hb/hbctrl/peer_drop.go
daemon/msgbus/main_test.go
daemon/msgbus/messages.go
daemon/nmon/main.go
daemon/nmon/main_cmd.go

This pull request includes the following changes:
- Renamed all `Hb*` structs and methods to `Heartbeat*` for improved readability and to align with their intended purpose in the heartbeat domain.
- Updated the `DaemonHeartbeatUpdated` JSON field name from `"hb"` to `"heartbeat"` for better clarity in data representation.
- Removed the `HbStatusUpdated` event and its associated logic as it is no longer necessary for the current implementation. 
These changes enhance code clarity and streamline functionality by removing outdated or unclear items.

Rename heartbeat-related identifiers for clarity and consistency

---

drivers/resdiskmd/main.go
drivers/resdiskmd/manifest.go
drivers/resdiskmd/text/kw/bitmap
util/md/main.go

mdadm removed the auto creation of bitmaps on big disks.
Add this provisioning keyword to let users decide if they want to keep using a bitmap for their md resources.

Add the "bitmap" kw to the disk.md driver

---

core/hbcfg/main.go
daemon/hb/hbucast/hbrx.go
daemon/hb/hbucast/hbtx.go
daemon/hb/hbucast/main.go

* b2.1 supports port scoping... not to encourage, but port to avoid migration hassles.
* add the port to the nodeMap to detect port changes, even in peer scoped configs
Example:
$ sudo om daemon hb status --name hb#1
STATUS  NODE    PEER    DESC
✅      dev2n3  dev2n1  11.29.1.13:9993 ← 11.29.1.11
✅      dev2n3  dev2n2  11.29.1.13:9993 ← 11.29.1.12
✅      dev2n3  dev2n1  → 11.29.1.11:9991
✅      dev2n3  dev2n2  → 11.29.1.12:9992
✅      dev2n1  dev2n2  11.29.1.11:9991 ← 11.29.1.12
✅      dev2n1  dev2n3  11.29.1.11:9991 ← 11.29.1.13
✅      dev2n1  dev2n2  → 11.29.1.12:9992
✅      dev2n1  dev2n3  → 11.29.1.13:9993
✅      dev2n2  dev2n1  11.29.1.12:9992 ← 11.29.1.11
✅      dev2n2  dev2n3  11.29.1.12:9992 ← 11.29.1.13
✅      dev2n2  dev2n1  → 11.29.1.11:9991
✅      dev2n2  dev2n3  → …

Support hb.ucast port scoping and fix the missed reconfiguration

---

daemon/imon/orchestration_provisioned.go

On a stopped and already provisioned service, the provision orchestration did not start.
Align the behaviour with the om2: make the provision start the leader instances.

Provision orchestration enhancement

---

core/keywords/keywords.go
core/object/core_doc.go
core/object/node_doc.go
core/object/node_keywords.go
daemon/api/api.yaml
daemon/api/codegen_client_gen.go
daemon/api/codegen_server_gen.go
daemon/api/codegen_type_gen.go
daemon/daemonapi/get_cluster_config_keywords.go
daemon/daemonapi/get_node_config_keywords.go
daemon/daemonapi/get_object_config_keywords.go
daemon/daemonapi/lib_config_keywords.go

- GET /api/cluster/config/keywords
- GET /api/node/{nodename}/config/keywords
- GET /api/object/path/{namespace}/{kind}/{name}/config/keywords
Also:
- Rename storeWithDriverKeywords → KeywordStoreWithDrivers to make it public
- Rename nodeKeywordStore → NodeKeywordStore to make it public

Add API endpoints to expose keyword definitions

---

core/resource/resource.go

Example:
cga                          down
└ instances
├ dev2n2                   undef  frozen idle
└ dev2n1                   undef  frozen start failed
└ resources
└ fs#1       ...O....  n/a    flag /dev/shm/opensvc/svc/cga/fs#1.flag
info: actions disabled, status disabled

Display the noaction and nostatus tags effect in res statuslog

---

util/scsi/mpath_persist.go
util/scsi/persistent_reservation.go
util/scsi/sg_persist.go

This pull request introduces the `formatKey` utility to ensure consistent SCSI key formatting. The utility applies zero-padding and truncation logic to standardize the keys to a fixed length ("0x" + 16 characters). Updates include:
- Implementing `formatKey` for appropriately formatted read registration or reservation keys.
- Replacing duplicated logic in `mpath_persist`, `persistent_reservation`, and `sg_persist` with the new utility to enhance maintainability and consistency.
- Resolving incorrect instance status representation when reserved by a local host with a key length less than the expected format (16 + 2).

Fix SCSI key formatting and registration status inconsistencies

---

daemon/daemonapi/lib_middleware.go
daemon/daemondata/apply_patch.go

This pull request makes two changes related to logging:
1. Reduces log verbosity when `apply_patch` requests the full dataset, ensuring logs remain concise.
2. Updates `logRequestLevelPerPath` paths to align with the revised API endpoint structure for accurate log level control.

Reduce log verbosity and update API log level paths
