opensvc/om3

- util/render/forest/main_test.go
Fix previous test with width 35
> Update forest test with larger width

- core/cluster/cluster_node.go
- core/object/node_config.go
- core/xconfig/main.go
- daemon/daemondata/apply_commit.go
- daemon/daemondata/apply_commit_remote_diff.go
- daemon/discover/cfg.go
- daemon/monitor/nmon/main.go
- daemon/monitor/nmon/main_cmd.go
Now the nmon global expect is propagated.
> Implement nmon events on remote patch commit

- cmd/factory.go
- cmd/node.go
- core/actionrouter/action.go
- core/commands/node_sysreport.go
- core/nodeaction/node.go
- core/object/core_action.go
- core/object/node_doc.go
- core/objectaction/object.go
- daemon/monitor/smon/crm_actions.go
- daemon/monitor/smon/main.go
- daemon/monitor/smon/main_cmd.go
- daemon/monitor/smon/orchestration_placed.go
- daemon/monitor/smon/orchestration_placed_at.go
- drivers/resfsflag/main.go
- drivers/resfsflag/manifest.go
- util/command/funcopts.go
- util/sysreport/config.go
For example, the node sysreport errors wouldn't get printed on stderr.
> placed-orchestrations

- core/cluster/cluster_node.go
- daemon/daemondata/stats.go
- daemon/monitor/nmon/main.go
- daemon/msgbus/messages.go
- go.mod
- go.sum
Nodes         dev2n1        dev2n2        dev2n3
score      | 94            95            95
load15m   | 0.1           0.0           0.1
mem       | 26/100%:1.93g 28/100%:1.93g 28/100%:1.93g
swap      | 6/100%:1.9g   1/100%:1.9g   1/100%:1.9g
> Implement node stats

- cmd/factory.go
- cmd/flags.go
- core/client/api/base.go
- core/client/api/get_events.go
- core/client/api/get_object_config_file.go
- core/client/api/get_object_selector.go
- core/client/api/get_relay_message.go
- core/client/request/request.go
- core/client/requester/h2/h2.go
- core/commands/node_events.go
- daemon/listener/routeraw/main.go
opensvc node event --filter HbPing --filter HbStale
opensvc node event --filter ObjectAggUpdated,path=foo
> opensvc node event --filter 

- cmd/daemon.go
- cmd/factory.go
- core/commands/daemon_join.go
- core/commands/daemon_leave.go
* shorter Short cmd help
* add a Long cmd help
* use --node instead of --jnode (drop GlobalOptions from the
daemon join options)
* tweak progress messages
> daemon join cmd tweaks

- daemon/daemondata/apply_commit_remote_diff.go
- daemon/daemondata/data.go
- daemon/daemondata/instance_config.go
- daemon/discover/cfg.go
- daemon/discover/fs_watcher.go
- daemon/discover/svcagg.go
- daemon/hb/hbctrl/peer_drop.go
- daemon/hb/main.go
- daemon/monitor/imon/main_cmd.go
- daemon/monitor/instcfg/main.go
- daemon/monitor/nmon/main.go
- daemon/monitor/nmon/main_cmd.go
- daemon/monitor/omon/main.go
- daemon/msgbus/messages.go
and rename MonConfigDone to InstanceConfigManagerDone
> Rename *Cfg* events to *Config*

- daemon/daemondata/stats.go
- daemon/monitor/nmon/main_cmd.go
Add the missing daemondata.T.SetNodeConfig() setter
Move the msgbus.NodeConfigUpdated event publication from nmon to
this daemondata setter.
> Fix the cluster.node.<node>.config section in daemondata

- daemon/msgbus/messages.go
- daemon/nmon/arbitrator.go
- daemon/nmon/main.go
- daemon/nmon/main_cmd.go
[nmon] publish ArbitratorError when arbitratorCheck detect error
[nmon] Fix missed updates of arbitrator config changes on cluster.conf
[nmon] Track frozen state to bypass split action when frozen
> Arbitrator improvement

- core/cluster/config.go
- core/object/node_keywords.go
- core/object/text/kw/node/listener.dns_sock_gid
- core/object/text/kw/node/listener.dns_sock_uid
- daemon/ccfg/main_cmd.go
- daemon/daemondata/apply_commit.go
- daemon/dns/main_cmd.go
- daemon/dns/uds.go
Support online value change too.
> Support newer pdns versions

- .github/workflows/go.yml
- cmd/factory.go
- cmd/flags.go
- core/client/api/get_logs.go
- core/client/client.go
- core/commands/node_logs.go
- core/commands/object_logs.go
- core/path/path.go
- daemon/api/api.yaml
- daemon/api/codegen_client_gen.go
- daemon/api/codegen_server_gen.go
- daemon/api/codegen_type_gen.go
- daemon/daemonapi/get_node_backlogs.go
- daemon/daemonapi/get_node_logs.go
- daemon/daemonapi/get_object_backlogs.go
- daemon/daemonapi/get_object_logs.go
Use event.Event as a SSE message format to factorize code with the "node events" command.
> Port the log commands to the new daemon api

- daemon/scheduler/main.go
- drivers/rescontainerdocker/main.go
- drivers/rescontainerkvm/main.go
- drivers/rescontainervbox/main.go
- drivers/resipcni/main.go
- drivers/resipnetns/main.go
- drivers/ressyncrsync/main.go
- util/logging/logging.go
- util/plog/main.go
Should be logged only if --caller is used.
> Fix caller info always logged

- core/oxcmd/node_drivers.go
> Example of parallel node querying in ox

- core/osagentservice/join_linux.go
- core/osagentservice/join_linux_test.go
- go.mod
- go.sum
> Support cgroup v2 in core/osagentservice

- daemon/imon/orchestration_started.go
1/ Prevent a imon to transition idle->ready if a peer imon is
already ready or starting
2/ Reset ready->idle if a peer imon published a ready or starting
state
Reproducer:
om foo* stop --wait
om cluster freeze --wait
om foo* thaw --wait
om cluster thaw --wait
sleep 4.9
om node freeze
> Fix a double start orchestration issue

- core/tui/instance.go
Placement non-optimal is unduly displayed.
> Fix a false positive in ox instance renderer

- daemon/daemonapi/lib_object_action.go
- daemon/daemonapi/post_object_action_abort.go
- daemon/daemonapi/post_object_action_delete.go
- daemon/daemonapi/post_object_action_freeze.go
- daemon/daemonapi/post_object_action_giveback.go
- daemon/daemonapi/post_object_action_provision.go
- daemon/daemonapi/post_object_action_purge.go
- daemon/daemonapi/post_object_action_restart.go
- daemon/daemonapi/post_object_action_start.go
- daemon/daemonapi/post_object_action_stop.go
- daemon/daemonapi/post_object_action_switch.go
- daemon/daemonapi/post_object_action_unfreeze.go
- daemon/daemonapi/post_object_action_unprovision.go
operator|admin|root required for:
abort
freeze
giveback
restart
start
stop
switch
unfreeze
admin|root required for:
delete
provision
purge
unprovision
> Add RBAC to the orchestated action POST API handlers

- core/objectaction/object.go
- core/om/factory.go
- core/omcmd/object_delete.go
- core/ox/factory.go
- core/oxcmd/object_delete.go
- Refactored object orchestration wait logic to better handle orchestration IDs and improve status verification (e.g., placed, frozen, provisioned states).
- Enhanced logging and error handling for greater debugging clarity and monitoring.
- Added asynchronous options to object delete commands for improved flexibility and performance.
> [crm] Improve object async orchestration and add async delete options

- daemon/daemoncmd/main.go
This pull request refactors the daemon process validation logic to include a retry mechanism for cases where reading the daemon PID command-line initially returns empty results.
> Fix unexpected daemon restart log message

- daemon/daemon/main.go
So we can use os.UserHomeDir()
> Make sure HOME is set in the daemon environment

- core/cluster/config.go
- core/object/actor.go
- core/object/ccfg.go
- core/resource/interfaces.go
- core/resource/ssh.go
- daemon/daemonapi/put_node_ssh_trust.go
- drivers/rescontainerkvm/main.go
- drivers/rescontainerlxc/main.go
- drivers/rescontainervbox/main.go
- drivers/resfsflag/main.go
- drivers/ressyncrsync/main.go
- drivers/ressynczfs/main.go
- util/sshnode/funcopts.go
- util/sshnode/main.go
- util/zfs/fs.go
- util/zfs/fs_destroy.go
- util/zfs/fs_rename.go
- util/zfs/ssh.go
This pull request focuses on improving the handling and initialization of SSH configurations. Key changes include:
- Refactored `actor.configureResource` to use `SetSSHKeyFile()` on applicable resources.
- Centralized SSH configuration management using the new `resource.SSH` structure.
- Updated drivers to utilize `NewSSHClient`, enhancing modularity and reusability.
- Introduced the `cluster.Config.SSHKeyFile()` method to fetch existing SSH key file paths if available.
- Enhanced the `sshnode` package with functional options for customizable SSH parameters like user, port, timeout, and private key files.
- Ensured `WithPrivateKeyFiles` in `sshnode` ignores empty private key entries to avoid unnecessary processing and potential errors.
- Adjusted ZFS operations to leverage the newly …
> Refactor SSH configuration and client initialization

- daemon/daemonapi/put_node_ssh_trust.go
- util/sshnode/main.go
This pull request ensures that `authorized_keys` and `known_hosts` files are properly synced after updates. This prevents potential inconsistencies in configurations and improves reliability.
> Sync SSH files after updates to prevent inconsistencies

- core/commoncmd/daemon_hb_status.go
- core/commoncmd/flags.go
- core/om/daemon.go
- core/om/factory.go
- core/omcmd/daemon_hb_status.go
- core/omcmd/object_create.go
- core/ox/daemon.go
- core/ox/factory.go
- core/oxcmd/daemon_hb_status.go
- core/oxcmd/object_create.go
- daemon/daemonsubsystem/hb.go
- daemon/hb/hbctrl/main.go
- daemon/hb/hbctrl/peer_watcher.go
- daemon/hb/hbdisk/hbrx.go
- daemon/hb/hbdisk/hbtx.go
- daemon/hb/hbmcast/hbrx.go
- daemon/hb/hbmcast/hbtx.go
- daemon/hb/hbrelay/hbrx.go
- daemon/hb/hbrelay/hbtx.go
- daemon/hb/hbucast/hbrx.go
- daemon/hb/hbucast/hbtx.go
Convert to keyops and append to command line keyops.
> Actually honor the --env flag of o[mx] create|deploy

- core/object/config_test.go
- core/object/core_config.go
- core/xconfig/main.go
- core/xconfig/validate.go
Missing deref trace init in this code path.
> Fix a stack on validate

- drivers/resfshost/main.go
- util/filesystems/linux.go
- util/filesystems/main.go
- util/filesystems/otheros.go
Try 4 times to kill processes blocking the umount if the mntpt is not a known important dir.
> Implement the "fuser -kmv; umount" loop on umount EBUSY

- CHANGELOG.md
- core/commoncmd/object_create.go
- core/omcmd/object_config_show.go
- core/omcmd/object_create.go
- core/oxcmd/object_create.go
* Remove all pivot to the rawconfig.T format logic
* Remove the multi-source logic
> Fix "om <path> create --config -"
